#!/bin/sh

set -e

# Do not put trailing slash in $1.

ubuntu ()
{
    MIRROR=http://archive.ubuntu.com/ubuntu
    DIST=trusty
    ARCH=amd64
    mkdir -p content
    cd content
    wget -nH -x -m \
        $MIRROR/dists/$DIST/Release \
        $MIRROR/dists/$DIST/Release.gpg \
        $MIRROR/dists/$DIST-backports/Release \
        $MIRROR/dists/$DIST-backports/Release.gpg \
        $MIRROR/dists/$DIST-updates/Release \
        $MIRROR/dists/$DIST-updates/Release.gpg \
        $MIRROR/dists/$DIST-security/Release \
        $MIRROR/dists/$DIST-security/Release.gpg \
        $MIRROR/dists/$DIST/main/binary-$ARCH/Packages.gz \
        $MIRROR/dists/$DIST/restricted/binary-$ARCH/Packages.gz \
        $MIRROR/dists/$DIST/universe/binary-$ARCH/Packages.gz \
        $MIRROR/dists/$DIST/multiverse/binary-$ARCH/Packages.gz \
        $MIRROR/dists/$DIST-backports/main/binary-$ARCH/Packages.gz \
        $MIRROR/dists/$DIST-backports/restricted/binary-$ARCH/Packages.gz \
        $MIRROR/dists/$DIST-backports/universe/binary-$ARCH/Packages.gz \
        $MIRROR/dists/$DIST-backports/multiverse/binary-$ARCH/Packages.gz \
        $MIRROR/dists/$DIST-security/main/binary-$ARCH/Packages.gz \
        $MIRROR/dists/$DIST-security/restricted/binary-$ARCH/Packages.gz \
        $MIRROR/dists/$DIST-security/universe/binary-$ARCH/Packages.gz \
        $MIRROR/dists/$DIST-security/multiverse/binary-$ARCH/Packages.gz \
        $MIRROR/dists/$DIST-updates/main/binary-$ARCH/Packages.gz \
        $MIRROR/dists/$DIST-updates/restricted/binary-$ARCH/Packages.gz \
        $MIRROR/dists/$DIST-updates/universe/binary-$ARCH/Packages.gz \
        $MIRROR/dists/$DIST-updates/multiverse/binary-$ARCH/Packages.gz
}

postgres ()
{
    MIRROR=http://apt.postgresql.org/pub/repos/apt
    DIST=trusty-pgdg
    ARCH=amd64
    mkdir -p content
    cd content
    wget -nH -x -m \
        $MIRROR/dists/$DIST/InRelease \
        $MIRROR/dists/$DIST/Release \
        $MIRROR/dists/$DIST/Release.gpg \
        $MIRROR/dists/$DIST/9.4/binary-$ARCH/Packages.gz \
        $MIRROR/dists/$DIST/9.5/binary-$ARCH/Packages.gz \
        $MIRROR/dists/$DIST/main/binary-$ARCH/Packages.gz
}

ubuntu
postgres
